---
deployment:
  tasks:
    - export DEPLOYPATH=/home/essenti1/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp menu.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R mail $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    